---
title: "02_Microbiome_analysis"
author: "kim soyeon"
date: "2026-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# 1. Import

## 1) package 
```{r}
# if (!requireNamespace("devtools", quietly = TRUE)){install.packages("devtools")}
# devtools::install_github("jbisanz/qiime2R")
library(qiime2R)
library(phyloseq)
library(readr)
library(stringr)
library(ggplot2)
library(decontam)
library(ggpubr)
library(vegan)
library(dplyr)
library(RColorBrewer)
library(patchwork)
library(tibble)
library(reshape2)
library(glue)
library(ggtext)
library(ggtext)
library(ggtext)
library(ggtext)
library(ggtext)
library(ggtext)
source("./Script/functions.R")

```


## 2) phyloseq
```{r}
phy <- readRDS("./Phyloseq/phy_F270R240_260812_v4.rds")
phy <- subset_samples(phy, control_status == "sample") %>% 
  prune_taxa(taxa_sums(.) > 0, .) # 1855 taxa and 50 samples

```




# 2. Check dataset


## 1) Depth 

### (1) total 
```{r}

sum(sample_sums(phy)) # 847149

summary(sample_sums(phy))
 # Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 #   5876   12330   17414   16943   21165   31707 

sd(sample_sums(phy)) #  6055.792

```
### (2) site
```{r}
phy.ac <- subset_samples(phy, site_id %in% "Ac") %>%
  prune_taxa(taxa_sums(.) > 0, .) #  1396 taxa and 25 samples

phy.fh <- subset_samples(phy, site_id %in% "Fh") %>%
  prune_taxa(taxa_sums(.) > 0, .) #  815 taxa and 25 samples

summarize_phy(ps = phy)
#   Total_reads Mean_Reads SD_Reads ASV_Count Phylum_Count Genus_Count Species_Count
#         <dbl>      <dbl>    <dbl>     <int>        <int>       <int>         <int>
# 1      847149      16943    6056.      1855           21         347           347
  
summarize_phyloseq_by_site(ps = phy, site_variable = "site_id")
#   Site  Mean_Reads SD_Reads ASV_Count Phylum_Count Genus_Count Species_Count
#   <chr>      <dbl>    <dbl>     <int>        <int>       <int>         <int>
# 1 Ac        16163.    5091.      1396           16         282           282
# 2 Fh        17723.    6906.       815           17         214           214

```


## 2) rerefraction 
```{r}

set.seed(42)

depths <- unique(round(seq(100, max( sample_sums(phy) ), length.out = 25)))

rarefaction_curve_data <- calculate_rarefaction_curves(
  phy,
  measures = c("Observed", "Shannon"),
  depths = rep(depths, each = 10)
)

rarefaction_curve_data_summary <- plyr::ddply(
  rarefaction_curve_data,
  c("Depth", "Sample", "Measure"),
  summarise,
  Alpha_diversity_mean = mean(Alpha_diversity, na.rm = TRUE),
  Alpha_diversity_sd = sd(Alpha_diversity, na.rm = TRUE)
)

meta_origin <- data.frame(sample_data(phy))
meta_origin$Sample <- rownames(meta_origin)

rarefaction_curve_data_summary$Sample <- stringr::str_replace_all(rarefaction_curve_data_summary$Sample, "^X", "")
rarefaction_curve_data_summary_verbose <- merge(rarefaction_curve_data_summary, meta_origin, by = "Sample")


```


```{r}
figureS4  <- ggplot(
  rarefaction_curve_data_summary_verbose,
  aes(
    x = Depth,
    y = Alpha_diversity_mean,
    colour = swab_type,
    group = Sample
  )
) +
  geom_line(alpha = 0.6) +
  facet_wrap(~ Measure, scales = "free_y") +
  scale_x_continuous(breaks = c(0, 1000, 2000, 5000, 10000, 15000, 20000)) +
  labs(colour = "Sample type") +
  theme_bw() +
  theme(axis.text.x = element_text(
    angle = 45,
    hjust = 1,
    vjust = 1
  ))

```


```{r}
ggsave(
  filename ="./Figures/FigureS4.png",
  plot = figureS4,
  width = 10, height = 4, dpi = 600
)

```



## 3) rarefy
```{r}
# 5876

set.seed(123)
phy_rar <- rarefy_even_depth(
  physeq = phy,
  sample.size = min(sample_sums(phy)),
  rngseed = 123,
  replace = FALSE,
  trimOTUs = TRUE,
  verbose = TRUE
)

# saveRDS(phy, "./Phyloseq/phy_F270R240_260812_v4_rarefy_5876.rds")
```

# Figure1

```{r}

phy_rar.ac <- subset_samples(phy_rar, site_id %in% "Ac") %>%
  prune_taxa(taxa_sums(.) > 0, .) #  1311 taxa and 25 samples ]

phy_rar.fh <- subset_samples(phy_rar, site_id %in% "Fh") %>%
  prune_taxa(taxa_sums(.) > 0, .) #  762 taxa and 25 samples



```


## 1) Diversity

### (1)beta
```{r}
col5 = brewer.pal(5, "Set2")
col5.2 = brewer.pal(5, "Set1")

# plot 
plot01 <- beta_plot(phyloseq = phy_rar,
                  type = "subject_id",
                  shap = "swab_type2",
                  seed=42,
                  plot="PCoA",
                  type_col = col5.2, 
                  col_inout   = c("in"),
                  col_right_left  = c("left"),
                  )

plot01$plots$wunifrac
plot01$plots$bray


# plot 
plot02 <- beta_plot(phyloseq = phy_rar.ac,
                  type = "subject_id",
                  shap = "swab_type2",
                  
                  seed=42,
                  plot="PCoA",
                  type_col = col5.2, 
                  col_inout   = c("in"),
                  col_right_left  = c("left"),
                  )

plot02$plots$wunifrac
plot02$plots$bray



# plot 
plot03 <- beta_plot(phyloseq = phy_rar.fh,
                  type = "subject_id",
                  shap = "swab_type2",
                  
                  seed=42,
                  plot="PCoA",
                  type_col = col5.2, 
                  col_inout   = c("out"),
                  col_right_left  = c("right"),
                  )

plot03$plots$wunifrac
plot03$plots$bray
```
### (2) alpha

```{r}


meta <- data.frame(sample_data(phy_rar))
alpha_diversity <-  estimate_richness(phy_rar, measures=c("Shannon", "Observed"))
rownames(alpha_diversity) <- str_replace(rownames(alpha_diversity), "^X", "")
alpha_Skin <- merge(alpha_diversity, meta , by = "row.names") %>% column_to_rownames("Row.names")

head(alpha_Skin)
```


```{r}
alpha_Skin$swab_type 
# 
# alpha_Skin_agg <- alpha_Skin %>%
#   group_by(SubjectID, Site2, Skin.type) %>%   # Subject 컬럼명 확인 필요
#   summarise(
#     Shannon = mean(Shannon, na.rm = TRUE),
#     .groups = "drop"
#   )
```



```{r}



plot04 <- alpha_plot(table = alpha_Skin, 
           x_ = "subject_id",
           y_ = "Shannon",
           colx_ = "swab_type2",
           ylim = 7.5, 
           col = col5) + 
  labs(y = "Shannon") +
  facet_grid(~site_id) +
  geom_pwc(method = "wilcoxon", 
           label = "{p.adj.signif}", 
           p.adjust.method = "BH",
                      step.increase = 0.1,

           hide.ns = TRUE)

plot04


plot05 <- alpha_plot(table = alpha_Skin, 
           x_ = "subject_id",
           colx_ = "swab_type2",
           y_ = "Observed",
           ylim = 430, 
           col = col5) + 
  labs(y = "Observed ASVs") +
  facet_grid(~site_id) +
  theme(legend.position = "right") + 
  geom_pwc(method = "wilcoxon", 
           label = "{p.adj.signif}",
           p.adjust.method = "BH", 
           step.increase = 0.1,
           hide.ns = TRUE
           )
plot05

```





## 3) taxonomy 
```{r}
phy #  1855 taxa and 50 samples
phy.gn <- phy %>% tax_glom(taxrank = "Genus") # 347 taxa and 50 samples
phy.gn.rel <- transform_sample_counts(phy.gn, function(x) x/sum(x))



phy.gn.rel.1 = phyloseq::filter_taxa(phy.gn.rel, function(x) mean(x) > .01, TRUE)   # 10


meta

tax.gn <- taxa_plot(melt = phyloseq::psmelt(phy.gn),
                    taxa = "Genus",
                    tax_otu = taxa_names(phy.gn.rel.1),
                    x_axis = "swab_type2",
                    phylum_or = "Actinobacteriota")

plot06 <- tax.gn$plot + ggh4x::facet_nested(~site_group + subject_id )
plot06

```




```{r}
figure1 <- (plot01$plots$bray  + theme( legend.position = "none")| 
              plot02$plots$bray + theme( legend.position = "none")| 
              plot03$plots$bray ) /
               (plot04 |  plot05)/
  plot06 + 
  patchwork::plot_annotation(tag_levels = "A")
                  

figure1


ggsave(plot = figure1,
       filename = "./Figures/Figure1.png", 
       width = 12, height = 10)

```



# Figure2
## 1) venn diagram 

```{R}


# install.packages("ComplexUpset")
library(ComplexUpset)
library(tidyr)
# 
# # swab type 확인
# table(sample_data(phy_rar)$swab_type2)
# 
# # 1) OTU table
# otu <- data.frame(as(otu_table(phy_rar), "matrix"))
# 
# if (taxa_are_rows(phy_rar)) {
#   otu <- t(otu) %>% data.frame()
# } else {
#   otu <- otu %>% data.frame()
# }
# 
# rownames(otu) <- str_replace(rownames(otu), "^X", "")
# 
# 
# # 2) metadata
# meta <- data.frame(sample_data(phy_rar))
# rownames(meta) <- str_replace(rownames(meta), "^X", "")
# 
# otu$swab_type2 <- meta[rownames(otu), "swab_type2"]
# 
# 
# # 3) Swab type별 ASV abundance 합산
# otu_swab <- otu %>%
#   group_by(swab_type2) %>%
#   summarise(
#     across(
#       .cols = everything(),
#       .fns = sum
#     )
#   ) %>%
#   column_to_rownames("swab_type2") %>%
#   as.data.frame()
# 
# 
# # 4) Presence / absence
# # 하나라도 검출되면 TRUE
# upset_data <- otu_swab %>%
#   t() %>%
#   as.data.frame() %>%
#   mutate(
#     across(
#       everything(),
#       ~ .x > 0
#     )
#   )
# 
# 
# # 5) Swab type 순서
# swab_order <- c(
#   "Copan",
#   "Eswab",
#   "Omni",
#   "Puritan_buffer",
#   "Puritan_gel"
# )
# 
# # 확인
# colnames(upset_data)
# table(meta$swab_type2)
# 
# 
# # 6) UpSet plot
# library(ComplexUpset)
# 
# figure2_upset <- ComplexUpset::upset(
#   upset_data,
#   intersect = swab_order,
#   name = "Swab type",
#   sort_intersections_by = "cardinality",
#   sort_sets = FALSE,
#   min_size = 1,
#   width_ratio = 0.15
# ) +
#   theme_bw() +
#   theme(
#     axis.text.x = element_text(
#       angle = 45,
#       hjust = 1
#     ),
#     axis.title = element_blank(),
#     panel.grid = element_blank()
#   )
# 
# figure2_upset



upset_swab_plot <- function(phyloseq,
                            site_variable = "site_group",
                            swab_variable = "swab_type2",
                            site = NULL,
                            swab_order = NULL,
                            min_size = 1) {
  library(phyloseq)
  library(dplyr)
  library(tibble)
  library(stringr)
  library(ComplexUpset)
  
  # --------------------------------------------------
  # 1. Subset site
  # --------------------------------------------------
  
  if (!is.null(site)) {
    phyloseq <- subset_samples(phyloseq, get(site_variable) %in% site) %>%
      prune_taxa(taxa_sums(.) > 0, .)
    
  }
  
  
  # --------------------------------------------------
  # 2. OTU table
  # --------------------------------------------------
  
  otu <- data.frame(as(otu_table(phyloseq), "matrix"))
  
  if (taxa_are_rows(phyloseq)) {
    otu <- t(otu) %>%
      data.frame()
  } else {
    otu <- otu %>%
      data.frame()
  }
  
  rownames(otu) <- str_replace(rownames(otu), "^X", "")
  
  
  # --------------------------------------------------
  # 3. Metadata
  # --------------------------------------------------
  
  meta <- data.frame(sample_data(phyloseq))
  
  rownames(meta) <- str_replace(rownames(meta), "^X", "")
  
  
  # --------------------------------------------------
  # 4. Add swab type
  # --------------------------------------------------
  
  otu$swab_type2 <- meta[rownames(otu), swab_variable]
  
  
  # --------------------------------------------------
  # 5. Swab type별 feature abundance 합산
  # --------------------------------------------------
  
  otu_swab <- otu %>%
    group_by(.data[[swab_variable]]) %>%
    summarise(across(.cols = everything(), .fns = sum)) %>%
    column_to_rownames(swab_variable) %>%
    as.data.frame()
  
  
  # --------------------------------------------------
  # 6. Presence / absence
  # --------------------------------------------------
  
  upset_data <- otu_swab %>%
    t() %>%
    as.data.frame() %>%
    mutate(across(everything(), ~ .x > 0))
  
  
  # --------------------------------------------------
  # 7. Swab order
  # --------------------------------------------------
  
  if (is.null(swab_order)) {
    swab_order <- colnames(upset_data)
    
  }
  
  
  # --------------------------------------------------
  # 8. UpSet plot
  # --------------------------------------------------
  
  p <- ComplexUpset::upset(
    upset_data,
    intersect = swab_order,
    name = "Swab type",
    sort_intersections_by = "cardinality",
    sort_sets = FALSE,
    min_size = min_size,
    width_ratio = 0.15
  ) +
    theme_bw() +
    theme(axis.title = element_blank(), panel.grid = element_blank())
  
  
  # --------------------------------------------------
  # 9. Return
  # --------------------------------------------------
  
  return(list(
    plot = p,
    data = upset_data,
    abundance = otu_swab
  ))
}
```


## ASV level 
```{r}

upset_all <- upset_swab_plot(
  phyloseq = phy,
  swab_order = c("Copan", "Eswab", "Omni", "Puritan_buffer", "Puritan_gel")
)

upset_all$plot



upset.ac <- upset_swab_plot(
  phyloseq = phy.ac,
  swab_order = c("Copan", "Eswab", "Omni", "Puritan_buffer", "Puritan_gel")
)


upset.fh <- upset_swab_plot(
  phyloseq = phy.fh,
  swab_order = c("Copan", "Eswab", "Omni", "Puritan_buffer", "Puritan_gel")
)


upset_all$plot
upset.ac$plot
upset.fh$plot
```



## Species level  
```{r}


upset_all.sp <- upset_swab_plot(
  phyloseq = tax_glom(phy, "Species"),
  swab_order = c("Copan", "Eswab", "Omni", "Puritan_buffer", "Puritan_gel")
)


upset.ac.sp <- upset_swab_plot(
  phyloseq = tax_glom(phy.ac, "Species"),
  swab_order = c("Copan", "Eswab", "Omni", "Puritan_buffer", "Puritan_gel")
)


upset.fh.sp <- upset_swab_plot(
  phyloseq = tax_glom(phy.fh, "Species"),
  swab_order = c("Copan", "Eswab", "Omni", "Puritan_buffer", "Puritan_gel")
)


upset_all.sp$plot
upset.ac.sp$plot
upset.fh.sp$plot

```



## 2) permanova
```{r}

set.seed(42)
dist <- phyloseq::distance(phy_rar, method = "bray")
dist2 <- phyloseq::distance(phy_rar, method = "jaccard")
meta   <- phy_rar %>% sample_data() %>% data.frame()
    
# PERMANOVA
set.seed(42)
Perm1    <- adonis2(
  dist ~ subject_id + swab_type2 + site_group,
  data         = meta,
  permutations = 9999,
  strata = meta$SubjectID,
  by ="margin"
) 


set.seed(42)
Perm2    <- adonis2(
  dist2 ~ subject_id +  swab_type2 + site_group,
  data         = meta,
  permutations = 9999,
  strata = meta$SubjectID,
  by ="margin"
) 

```


```{r}
Perm1
#            Df SumOfSqs      R2      F Pr(>F)    
# subject_id  4   6.1375 0.40835  9.1436 0.0001 ***
# swab_type2  4   0.4471 0.02975  0.6660 0.9361    
# site_group  1   1.7331 0.11531 10.3276 0.0001 ***
# Residual   40   6.7124 0.44660                   
# Total      49  15.0301 1.00000                   

  
Perm2
#            Df SumOfSqs      R2      F Pr(>F)    
# subject_id  4   5.8255 0.32916 6.2042 0.0001 ***
# swab_type2  4   0.7121 0.04024 0.7584 0.9066    
# site_group  1   1.7708 0.10006 7.5437 0.0001 ***
# Residual   40   9.3897 0.53055                  
# Total      49  17.6982 1.00000                  

```





## 3) swab distance 

### (1) Within subject x site pairwise distance
```{r}

# Distance is calculated between the five swabs collected from the same
# subject and site. phy_rar is used to keep this analysis consistent with
# the PERMANOVA above.
get_within_swab_distance <- function(phyloseq, method = "bray", binary = FALSE) {
  meta_dist <- data.frame(sample_data(phyloseq), check.names = FALSE)
  meta_dist$sample_id <- sample_names(phyloseq)
  
  dist_all <- phyloseq::distance(
    phyloseq,
    method = method,
    binary = binary
  ) %>%
    as.matrix()
  
  group_list <- split(
    meta_dist,
    interaction(meta_dist$subject_id, meta_dist$site_group, drop = TRUE)
  )
  
  distance_list <- lapply(group_list, function(x) {
    sample_ids <- x$sample_id
    
    if (length(sample_ids) < 2) return(NULL)
    
    sample_pair <- combn(sample_ids, 2)
    
    data.frame(
      subject_id = x$subject_id[1],
      site_group = x$site_group[1],
      swab_1 = x$swab_type2[match(sample_pair[1, ], x$sample_id)],
      swab_2 = x$swab_type2[match(sample_pair[2, ], x$sample_id)],
      distance = dist_all[cbind(sample_pair[1, ], sample_pair[2, ])],
      stringsAsFactors = FALSE
    )
  })
  
  bind_rows(distance_list) %>%
    mutate(
      swab_pair = ifelse(
        swab_1 < swab_2,
        paste(swab_1, swab_2, sep = " - "),
        paste(swab_2, swab_1, sep = " - ")
      ),
      distance_method = ifelse(binary, "Jaccard", "Bray-Curtis")
    )
}


swab_distance_bray <- get_within_swab_distance(
  phyloseq = phy_rar,
  method = "bray"
)

swab_distance_jaccard <- get_within_swab_distance(
  phyloseq = phy_rar,
  method = "jaccard",
  binary = TRUE
)

swab_distance <- bind_rows(
  swab_distance_bray,
  swab_distance_jaccard
)


figure2_distance <- ggplot(
  swab_distance,
  aes(x = swab_pair, y = distance, colour = site_group)
) +
  geom_boxplot(outlier.shape = NA, colour = "grey40") +
  geom_point(
    position = position_jitterdodge(jitter.width = 0.12, dodge.width = 0.75),
    alpha = 0.8
  ) +
  facet_wrap(~distance_method, scales = "free_y") +
  labs(x = "Swab pair", y = "Within subject x site distance", colour = "Site") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  )

figure2_distance

```


## 4) taxa recovery rate
```{r}

# For each subject x site, the denominator is the observed taxa pool across
# all five swabs (union), not a biological gold standard.
otu_recovery <- data.frame(as(otu_table(phy), "matrix"), check.names = FALSE)

if (taxa_are_rows(phy)) {
  otu_recovery <- t(otu_recovery) %>%
    data.frame(check.names = FALSE)
}

otu_recovery <- otu_recovery %>%
  rownames_to_column("sample_id") %>%
  pivot_longer(
    cols = -sample_id,
    names_to = "taxon_id",
    values_to = "abundance"
  )

meta_recovery <- data.frame(sample_data(phy), check.names = FALSE)
meta_recovery$sample_id <- sample_names(phy)

taxa_recovery <- otu_recovery %>%
  left_join(
    meta_recovery %>%
      select(sample_id, subject_id, site_group, swab_type2),
    by = "sample_id"
  ) %>%
  mutate(detected = abundance > 0) %>%
  group_by(subject_id, site_group) %>%
  mutate(union_taxa = n_distinct(taxon_id[detected])) %>%
  group_by(subject_id, site_group, swab_type2, sample_id, union_taxa) %>%
  summarise(
    detected_taxa = sum(detected),
    recovery_rate = detected_taxa / first(union_taxa),
    .groups = "drop"
  )


figure2_recovery <- ggplot(
  taxa_recovery,
  aes(x = swab_type2, y = recovery_rate, group = interaction(subject_id, site_group))
) +
  geom_line(colour = "grey70", alpha = 0.7) +
  geom_point(aes(colour = swab_type2), size = 2.5) +
  facet_wrap(~site_group) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(x = "Swab type", y = "Taxa recovery rate", colour = "Swab type") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank(),
    legend.position = "none"
  )

figure2_recovery

```


## 5) taxon detection prevalence
```{r}

# Genus-level prevalence: proportion of subject x site samples in which each
# genus was detected for a given swab type.
phy.gn.detect <- tax_glom(phy, taxrank = "Genus") %>%
  prune_taxa(taxa_sums(.) > 0, .)

otu_detect <- data.frame(as(otu_table(phy.gn.detect), "matrix"), check.names = FALSE)

if (taxa_are_rows(phy.gn.detect)) {
  otu_detect <- t(otu_detect) %>%
    data.frame(check.names = FALSE)
}

tax_detect <- data.frame(tax_table(phy.gn.detect)) %>%
  rownames_to_column("taxon_id") %>%
  select(taxon_id, Genus)

meta_detect <- data.frame(sample_data(phy.gn.detect), check.names = FALSE)
meta_detect$sample_id <- sample_names(phy.gn.detect)

detection_prevalence <- otu_detect %>%
  rownames_to_column("sample_id") %>%
  pivot_longer(
    cols = -sample_id,
    names_to = "taxon_id",
    values_to = "abundance"
  ) %>%
  left_join(tax_detect, by = "taxon_id") %>%
  left_join(
    meta_detect %>%
      select(sample_id, subject_id, site_group, swab_type2),
    by = "sample_id"
  ) %>%
  mutate(
    detected = abundance > 0,
    Genus = ifelse(is.na(Genus) | Genus == "", "Unclassified", as.character(Genus))
  ) %>%
  group_by(Genus, swab_type2) %>%
  summarise(
    detection_prevalence = mean(detected),
    n_detected = sum(detected),
    n_samples = n(),
    .groups = "drop"
  )


# Display the 20 genera with the highest mean prevalence across swab types.
major_detected_genera <- detection_prevalence %>%
  group_by(Genus) %>%
  summarise(mean_prevalence = mean(detection_prevalence), .groups = "drop") %>%
  slice_max(mean_prevalence, n = 20, with_ties = FALSE) %>%
  pull(Genus)

figure2_prevalence <- detection_prevalence %>%
  filter(Genus %in% major_detected_genera) %>%
  mutate(Genus = factor(Genus, levels = rev(major_detected_genera))) %>%
  ggplot(aes(x = swab_type2, y = Genus, fill = detection_prevalence)) +
  geom_tile(colour = "white") +
  geom_text(aes(label = scales::percent(detection_prevalence, accuracy = 1)), size = 3) +
  scale_fill_gradient(low = "white", high = "#2166AC", limits = c(0, 1)) +
  labs(x = "Swab type", y = "Genus", fill = "Detection\nprevalence") +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  )

figure2_prevalence

```


## 6) concordance of major taxa
```{r}

# Spearman concordance of the major genus relative-abundance profiles between
# swabs collected from the same subject and site.
phy.gn.major <- transform_sample_counts(phy.gn.detect, function(x) x / sum(x))
major_taxa <- names(sort(taxa_sums(phy.gn.major), decreasing = TRUE))[1:20]
phy.gn.major <- prune_taxa(major_taxa, phy.gn.major)

otu_concordance <- data.frame(as(otu_table(phy.gn.major), "matrix"), check.names = FALSE)

if (taxa_are_rows(phy.gn.major)) {
  otu_concordance <- t(otu_concordance) %>%
    data.frame(check.names = FALSE)
}

meta_concordance <- data.frame(sample_data(phy.gn.major), check.names = FALSE)
meta_concordance$sample_id <- sample_names(phy.gn.major)

concordance_group <- split(
  meta_concordance,
  interaction(meta_concordance$subject_id, meta_concordance$site_group, drop = TRUE)
)

major_taxa_concordance <- lapply(concordance_group, function(x) {
  if (nrow(x) < 2) return(NULL)
  
  sample_pair <- combn(x$sample_id, 2)
  
  data.frame(
    subject_id = x$subject_id[1],
    site_group = x$site_group[1],
    swab_1 = x$swab_type2[match(sample_pair[1, ], x$sample_id)],
    swab_2 = x$swab_type2[match(sample_pair[2, ], x$sample_id)],
    spearman_rho = apply(sample_pair, 2, function(z) {
      cor(
        as.numeric(otu_concordance[z[1], ]),
        as.numeric(otu_concordance[z[2], ]),
        method = "spearman"
      )
    }),
    stringsAsFactors = FALSE
  )
}) %>%
  bind_rows() %>%
  mutate(
    swab_pair = ifelse(
      swab_1 < swab_2,
      paste(swab_1, swab_2, sep = " - "),
      paste(swab_2, swab_1, sep = " - ")
    )
  )


figure2_concordance <- ggplot(
  major_taxa_concordance,
  aes(x = swab_pair, y = spearman_rho, colour = site_group)
) +
  geom_boxplot(outlier.shape = NA, colour = "grey40") +
  geom_point(
    position = position_jitterdodge(jitter.width = 0.12, dodge.width = 0.75),
    alpha = 0.8
  ) +
  labs(
    x = "Swab pair",
    y = "Spearman correlation of top 20 genera",
    colour = "Site"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    panel.grid = element_blank()
  )

figure2_concordance

```

## 7) ancom-bc2 paire (X)
```{r}
# library(ANCOMBC)
# library(tidyr)
# library(purrr)
# library(ggplot2)
# 
# ```
# 
# 
# ```{r}
# set.seed(42)
# 
# ancombc2_genus <- ancombc2(
#   data = phy,
#   tax_level = "Genus",
#   fix_formula = "swab_type2 + site_group + age",
#   rand_formula = "(1 | subject_id)",
#   p_adj_method = "BH", prv_cut = 0.10, lib_cut = 0,
#   pseudo_sens = TRUE,
#   group = "swab_type2", 
#   struc_zero = TRUE, neg_lb = TRUE, alpha = 0.05, global = TRUE, pairwise = TRUE, n_cl = 4, verbose = TRUE,
#   iter_control = list( tol = 0.01, max_iter = 20, verbose = FALSE ),
#   em_control = list(tol = 1e-5, max_iter = 100),
#   lme_control = lme4::lmerControl(),
#   mdfdr_control = list(fwer_ctrl_method = "holm", B = 100)
# )
# ```
# 
# 
# ```{r}
# 
# AB_barplot <- ancombcVizhelper::make_barplots(
#   out = ancombc2_genus,
#   result = "res_pair",
#   prefix = "swab_type2",
#   sensitivity = "keep",
#   show_all = TRUE,
#   group_order = "mean",
#   order = "asc",  
#   groupnames = FALSE
# 
# )
# 
# AB_barplot$plot
```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


